@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjcwMDQwNTV9.orfadLRdCRcRmXKxCE_mLXf6O8S2VEBXg6Tn1_0PgxY


### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "hammer",
  "email": "hammer@test.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "hammer@test.com",
  "password": "password"
}

### Products index
GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NjYzMTI2MzF9.xBWrc23kYpPu-OPBqe8f5Fd3iP78pgfMUYVGtxgr_3w

### Products show
GET http://localhost:3000/products/9.json

### Products create
POST http://localhost:3000/products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "name": "Adidas Arsenal Away Jersey",
    "price": 89, 
    "description": "Arsenal Away Jersey for the 2022/23 soccer season!", 
    "image_url": "https://images.dickssportinggoods.com/is/image/GolfGalaxy/21ADIMCSRS22WRPJSATH?qlt=70&wid=600&fmt=webp",
    
}

### Products destroy 
DELETE http://localhost:3000/products/9.json
Authorization: Bearer {{jwt}}

### Products patch
PATCH http://localhost:3000/products/13.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "price": 220 
}


### ORDERS CREATE ###
POST http://localhost:3000/orders.json 
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "product_id": "1",
  "quantity": "1"

}


### ORDERS SHOW ### 
GET http://localhost:3000/orders/5.json 
Authorization: Bearer {{jwt}}
Content-Type: application/json


### ORDERS INDEX ###
GET http://localhost:3000/orders.json  
Authorization: Bearer {{jwt}}
Content-Type: application/json